config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users do 
      resources :profiles
    end
  end

  get 'signup'     => 'admin/users#new'
  get 'signin'     => 'sessions#new'
  post 'signin'    => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  get 'receipt'    => 'home#send_receipt'
  get 'pdftest'    => 'home#pdftest'

  root 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  acts_as_mappable :default_units => :kms, :distance_field_name => :distance

  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  def admin?
    self.role == 'admin'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < SecureApplicationController
  include SessionsHelper

  before_filter :check_login, except: [:new, :create]

  def index
    @distance = 10

    if params[:search]
      @search_term = params[:search][:search_term] if params[:search][:search_term]
      @distance    = params[:search][:within] if params[:search][:within]
    end

    if(@search_term)
      @users = Profile.joins(:user) # loads the user and makes it available for the query
                      .within(@distance, :origin => Profile.first, :units => :kms) # checks the @distance < ---- this is from geokit
                      .where("users.email LIKE ? OR users.name LIKE ?", "%#{@search_term}%", "%#{@search_term}%") # this checks the name or email
                      .collect(&:user) # this collexts it into an array
                      
    else
      @users = Profile.within(@distance, :origin => Profile.first, :units => :kms)
                      .collect(&:user)
    end

  end

  def new
    @user = User.new
    @user.build_profile # create the blank profile
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Successfully updated profile'
      redirect_to admin_user_path(@user)
    else
      flash[:danger] = 'Failed to update profile'
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, flash: { success: 'Successfully created account' }
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                 profile_attributes: [:id, :location, :birthdate, :avatar])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def pdftest
    @users = User.all
    @asset_path = "#{Rails.root}/app/assets/images"
    render :pdftest, handlers: [:prawn], formats: [:pdf]
  end

  def send_receipt
    @users      = User.all
    @attachment = render_to_string :pdftest, handlers: [:prawn], formats: [:pdf]
    @email      = ReceiptMailer.email_with_attachment(User.first, @attachment)
    @email.deliver

    # render :send_receipt, handlers: [:html], formats: [:erb]
    redirect_to root_path
  end

end

app/controllers/secure_application_controller.rb
class SecureApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'layouts/admin'

  include SessionsHelper

  private

  def check_login
    unless logged_in? and current_user.admin?
      flash[:danger] = 'You must be logged in'
      redirect_to signin_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])

    if @user and @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if @user.admin?
        redirect_to admin_users_path, flash: { success: "Welcome back #{@user.name}" }
      else
        redirect_to root_path, flash: { success: "Welcome back #{@user.name}" }
      end
    else
      flash.now[:danger] = 'Invalid email and password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id) if logged_in?
    redirect_to root_path, flash: { success: 'Logged out!' }
  end
end

app/controllers/users_controller.rb
class UsersController < SecureApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, flash: { success: 'Successfully created account' }
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-xs-12">

    <div class="page-header">
      <h1>Update Profile</h1>
    </div>

    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |error| %>
        <div class="alert alert-danger">
          <%= error %>
        </div>
      <% end %>
    <% end %>

    <%= form_for(@user, url: admin_user_path(current_user), method: :put, :html => {:multipart => true}) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <%= f.fields_for :profile do |p| %>

        <div class="form-group">
          <%= p.label :location %>
          <%= p.text_field :location, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= p.label :birthdate %>
          <%= p.text_field :birthdate, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= p.label :avatar %>
          <%= p.file_field :avatar, class: 'form-control' %>
        </div>

      <% end %>

      <div class="form-group">
        <p><i>Fill in the fields below to change your password.</i></p>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.text_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1>Users</h1>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= form_for(:search, url: admin_users_path, method: :get, :html => { class: 'form-inline pull-right' }) do |f| %>
          <div class="form-group">
            <div class="input-group">
              <%= f.select :within, [5, 10, 15, 20, 40, 80, 120], { selected: @distance }, { class: 'form-control input-sm' } %>
              <div class="input-group-addon">KM</div>
            </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <%= f.text_field :search_term, class: 'form-control input-sm', value: @search_term %>
            </div>
          </div>
          <%= f.submit :Search, class: 'btn btn-primary btn-sm' %>
        <% end %>
      </div>
    </div>

    <table class="table table-striped table-hover">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Since</th>
        <th>Distance To</th>
        <th>Action</th>
      </tr>

      <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.profile.distance_to(current_user.profile, :units => :kms).round(1) %> KM</td>
        <td><%= link_to 'View', admin_user_path(user) %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 col-lg-offset-4">

    <div class="page-header">
      <h1>Sign Up</h1>
    </div>

    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |error| %>
        <div class="alert alert-danger">
          <%= error %>
        </div>
      <% end %>
    <% end %>

    <%= form_for(@user, url: admin_users_path) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <%= f.fields_for :profile do |p| %>

        <div class="form-group">
          <%= p.label :location %>
          <%= p.text_field :location, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= p.label :birthdate %>
          <%= p.text_field :birthdate, class: 'form-control' %>
        </div>

      <% end %>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.text_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Sign up', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <%= image_tag(@user.profile.avatar.thumb.url, class: 'img-thumbnail') if @user.profile.avatar? %>
  </div>
  <div class="col-xs-9">
    <h1><%= @user.name %><small> <%= @user.profile.location %></h1>
    <p>Born <%= @user.profile.birthdate %></p>
  </div>
</div>

app/views/home/send_receipt.html.erb
<h1>Sent the receipt to <%= @users.first.email %> !</h1>

app/views/layouts/_footer.html.erb
<div class="container" id="footer">
  <div class="row">
    <div class="col-xs-12">
      <p>All content &copy; Kevin 2014</p>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: "alert alert-#{name}" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Sample App', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Edit Profile', edit_admin_user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', signout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', signin_path %></li>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AToZ Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<%= render 'layouts/messages' %>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AToZ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<%= render 'layouts/messages' %>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 col-lg-offset-4">

    <div class="page-header">
      <h1>Sign Up</h1>
    </div>

    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |error| %>
        <div class="alert alert-danger">
          <%= error %>
        </div>
      <% end %>
    <% end %>

    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.text_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Sign up', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>